/**
 * Spanish text for the 40-decision record, keyed by decision number. Only the
 * human-written fields are translated; kind, stakes, confidences, results, and
 * audience names are locale-independent and stay on the English record. The
 * data layer merges these over the English decisions, so any number left out
 * here simply falls back to English.
 */
export interface DecisionText {
  title: string
  options: string[]
  gutOpt: string
  worry: string
  finalOpt: string
  why: string
  gaveUp: string
  tripwire: string
  whatHappened: string
  lesson: string
}

export const DECISIONS_TEXT_ES: Record<number, DecisionText> = {
  1: {
    title: "Reconstruir la búsqueda de reservas o parchar la actual",
    options: ["Parchar la búsqueda actual", "Reconstruir la búsqueda desde cero"],
    gutOpt: "Parchar la búsqueda actual", worry: "Seguimos parchando para siempre",
    finalOpt: "Reconstruir la búsqueda desde cero", why: "Los parches se acumulaban y nadie entendía ya el código",
    gaveUp: "Dos sprints limpios", tripwire: "Si la reconstrucción pasa de tres sprints, parar y lanzar el parche",
    whatHappened: "La reconstrucción tomó dos sprints y las quejas de búsqueda bajaron a la mitad", lesson: "Cuando el código asusta al equipo, esa es la señal para reconstruir.",
  },
  2: {
    title: "Lanzar recordatorios con SMS o solo email",
    options: ["Solo email para el launch", "Email y SMS juntos"],
    gutOpt: "Email y SMS juntos", worry: "Los costos de SMS se disparan",
    finalOpt: "Solo email para el launch", why: "El email cubría el 80 por ciento del valor y podíamos añadir SMS después",
    gaveUp: "Un launch más llamativo", tripwire: "Si las tasas de apertura bajan del 40 por ciento, añadir SMS",
    whatHappened: "Los recordatorios por email redujeron las ausencias y SMS se lanzó un mes después", lesson: "Lanzar el 80 por ciento primero nos dio datos reales.",
  },
  3: {
    title: "Comprometer una fecha de marzo para la reescritura del calendario",
    options: ["Comprometer la fecha de marzo", "Esperar la fecha hasta terminar el spike"],
    gutOpt: "Comprometer la fecha de marzo", worry: "La estimación de Marco es floja",
    finalOpt: "Comprometer la fecha de marzo", why: "Ventas necesitaba algo que decirle al pipeline",
    gaveUp: "Holgura en el calendario", tripwire: "Si el spike se alarga, mover la fecha antes de que ventas la mencione",
    whatHappened: "La reescritura se movió dos semanas y ventas tuvo que retractar una fecha", lesson: "Una estimación floja no es una fecha.",
  },
  4: {
    title: "Elegir el proveedor de SMS para recordatorios",
    options: ["Twilio", "MessageBird"],
    gutOpt: "Twilio", worry: "El precio de Twilio a escala",
    finalOpt: "Twilio", why: "El equipo ya conocía la API y la documentación era sólida",
    gaveUp: "Una tarifa un poco más barata", tripwire: "Si el gasto mensual de SMS pasa de 2k, reconsiderar MessageBird",
    whatHappened: "La integración tomó dos días y la entrega fue fiable", lesson: "Las herramientas conocidas se lanzan más rápido que las baratas.",
  },
  5: {
    title: "Cubrir la vacante de PM ahora o esperar",
    options: ["Contratar la transferencia interna", "Seguir buscando un externo más fuerte"],
    gutOpt: "Contratar la transferencia interna", worry: "Puede ser muy junior para el roadmap",
    finalOpt: "Contratar la transferencia interna", why: "Conocía el producto y el equipo confiaba en ella",
    gaveUp: "Una contratación externa más sénior", tripwire: "Si tiene problemas con el roadmap para el segundo mes, emparejarla con un PM sénior",
    whatHappened: "Se adaptó rápido y fue dueña de recordatorios de principio a fin", lesson: "El conocimiento del producto supera a un currículum más grande en áreas propias.",
  },
  6: {
    title: "Recortar las reservas recurrentes del launch Q2",
    options: ["Mantener las reservas recurrentes", "Recortar las reservas recurrentes al próximo trimestre"],
    gutOpt: "Mantener las reservas recurrentes", worry: "Ventas lo prometió",
    finalOpt: "Recortar las reservas recurrentes al próximo trimestre", why: "Estaba a medias y habría retrasado todo lo demás",
    gaveUp: "Una promesa que hizo ventas", tripwire: "Si dos tratos enterprise lo necesitan, reincorporarlo",
    whatHappened: "El resto del launch salió a tiempo y lo recurrente llegó en Q3", lesson: "Recortar lo que estaba a medias protegió todo el launch.",
  },
  7: {
    title: "Decirle a un buen ingeniero que su proyecto favorito murió",
    options: ["Terminar el proyecto y reasignarlo", "Darle un sprint más"],
    gutOpt: "Terminar el proyecto y reasignarlo", worry: "Que renuncie",
    finalOpt: "Terminar el proyecto y reasignarlo", why: "No tenía camino a los clientes y merecía la verdad",
    gaveUp: "Una conversación cómoda", tripwire: "Si se desconecta, armar un plan de crecimiento real",
    whatHappened: "Estuvo frustrado una semana, luego asumió el onboarding y le fue bien", lesson: "Di lo difícil pronto y dale un lugar donde aterrizar.",
  },
  8: {
    title: "Aceptar la fecha de launch de un socio",
    options: ["Aceptar la fecha del socio", "Pedir dos semanas más"],
    gutOpt: "Aceptar la fecha del socio", worry: "Subestimamos la integración",
    finalOpt: "Aceptar la fecha del socio", why: "El socio tenía una campaña de marketing reservada",
    gaveUp: "Un margen seguro", tripwire: "Si la especificación de la integración crece, renegociar la fecha",
    whatHappened: "La fecha se movió y el backlog de soporte se duplicó durante la corrida", lesson: "La fecha de marketing de otro no es tu fecha de ingeniería.",
  },
  9: {
    title: "Ir por enterprise o apostarle a SMB",
    options: ["Seguir enfocado en SMB", "Empezar a construir para enterprise"],
    gutOpt: "Seguir enfocado en SMB", worry: "Perdemos los tratos más grandes",
    finalOpt: "Empezar a construir para enterprise", why: "Tres funciones de SMB ya desbloqueaban enterprise con pequeñas adiciones",
    gaveUp: "Un roadmap más simple", tripwire: "Si el trabajo enterprise frena la velocidad de SMB, retroceder",
    whatHappened: "Dos pilotos enterprise firmaron sin afectar el ritmo de SMB", lesson: "El puente a enterprise era más corto de lo que parecía.",
  },
  10: {
    title: "Dividir el equipo de reservas en dos pods",
    options: ["Mantener un equipo", "Dividir en dos pods enfocados"],
    gutOpt: "Dividir en dos pods enfocados", worry: "Perdemos contexto compartido",
    finalOpt: "Dividir en dos pods enfocados", why: "Un equipo estaba repartido en demasiadas superficies",
    gaveUp: "Cobertura cruzada fácil", tripwire: "Si los pods se separan, añadir una sincronización semanal",
    whatHappened: "Ambos pods avanzaron más rápido y la titularidad se aclaró", lesson: "El enfoque superó a la flexibilidad para un equipo saturado.",
  },
  11: {
    title: "Añadir un ajuste de margen de reserva o mantenerlo fijo",
    options: ["Mantener el margen fijo", "Añadir un margen configurable"],
    gutOpt: "Añadir un margen configurable", worry: "Proliferación de ajustes",
    finalOpt: "Añadir un margen configurable", why: "Los técnicos de campo lo pedían y era un cambio pequeño",
    gaveUp: "Una página de ajustes más simple", tripwire: "Si menos del 10 por ciento lo usa, ocultarlo en ajustes avanzados",
    whatHappened: "Cerca de una cuarta parte de los pros lo configuró y los tickets de doble reserva bajaron", lesson: "Un pequeño ajuste puede eliminar toda una clase de tickets.",
  },
  12: {
    title: "Elegir la herramienta de analítica",
    options: ["Amplitude", "Mixpanel"],
    gutOpt: "Amplitude", worry: "Esfuerzo de migración",
    finalOpt: "Amplitude", why: "El equipo prefería el modelo de consultas y el precio encajaba con nuestro volumen",
    gaveUp: "Una herramienta que dos personas ya conocían", tripwire: "Si los dashboards quedan sin uso un mes, reconsiderar",
    whatHappened: "La adopción fue alta y los embudos dieron forma al roadmap", lesson: "Elige la herramienta que el equipo realmente abrirá.",
  },
  13: {
    title: "Contratar un contractor o un ingeniero de tiempo completo",
    options: ["Traer un contractor", "Contratar a tiempo completo"],
    gutOpt: "Contratar a tiempo completo", worry: "Más lento de cubrir",
    finalOpt: "Contratar a tiempo completo", why: "El trabajo era central y duraría más que un contrato",
    gaveUp: "Velocidad", tripwire: "Si la búsqueda pasa de seis semanas, cubrir con un contractor",
    whatHappened: "La vacante se cubrió en cinco semanas y fue dueño de la superficie de pagos", lesson: "El trabajo central merece un dueño a tiempo completo.",
  },
  14: {
    title: "Lanzar el rediseño antes o después de la temporada alta",
    options: ["Lanzar antes de la temporada alta", "Esperar hasta después"],
    gutOpt: "Esperar hasta después", worry: "El impulso se estanca",
    finalOpt: "Esperar hasta después", why: "Un rediseño durante el pico de reservas era muy arriesgado",
    gaveUp: "Victorias tempranas", tripwire: "Si un competidor lanza primero, reevaluar",
    whatHappened: "Se lanzó justo después del pico sin interrumpir las reservas", lesson: "Protege la temporada alta, aunque esperar se sienta lento.",
  },
  15: {
    title: "Abrir la API a socios ahora o después",
    options: ["Mantener la API interna por ahora", "Abrir una API para socios"],
    gutOpt: "Mantener la API interna por ahora", worry: "Carga de soporte de los socios",
    finalOpt: "Abrir una API para socios", why: "Dos socios estaban listos para construir y abrió un canal",
    gaveUp: "Un trimestre tranquilo", tripwire: "Si los tickets de socios abruman al equipo, limitar el acceso",
    whatHappened: "Dos integraciones se lanzaron e impulsaron reservas por referido", lesson: "Una API limitada abrió un canal sin ahogarnos.",
  },
  16: {
    title: "Incluir reembolsos en la corrección de pagos o diferir",
    options: ["Corregir solo los cargos", "Corregir cargos y reembolsos juntos"],
    gutOpt: "Corregir cargos y reembolsos juntos", worry: "Ampliación de scope en una corrección urgente",
    finalOpt: "Corregir solo los cargos", why: "Los cargos duplicados eran el incendio; los reembolsos podían seguir",
    gaveUp: "Una corrección completa de una vez", tripwire: "Si las quejas de reembolso suben, dar seguimiento rápido",
    whatHappened: "La corrección de cargos salió rápido y los reembolsos siguieron dos semanas después", lesson: "En una corrección urgente, apaga el incendio primero.",
  },
  17: {
    title: "Mover al equipo de Jordan al rediseño de reservas",
    options: ["Mantener al equipo de Jordan donde está", "Moverlos al rediseño"],
    gutOpt: "Moverlos al rediseño", worry: "Jordan se siente tomado por sorpresa",
    finalOpt: "Moverlos al rediseño", why: "El rediseño necesitaba músculo de diseño y eran el mejor ajuste",
    gaveUp: "El proyecto en el que estaban", tripwire: "Si la moral baja, revisar la asignación",
    whatHappened: "El rediseño mejoró y Jordan estuvo bien una vez avisado pronto", lesson: "Avísale a Jordan antes del movimiento, no después.",
  },
  18: {
    title: "Crear una app móvil o mejorar la web móvil",
    options: ["Mejorar la web móvil", "Crear una app nativa"],
    gutOpt: "Crear una app nativa", worry: "Estiramos demasiado al equipo",
    finalOpt: "Mejorar la web móvil", why: "La mayoría de las reservas eran únicas y no necesitaban instalación",
    gaveUp: "Una presencia llamativa en la tienda de apps", tripwire: "Si el uso móvil recurrente crece, reconsiderar lo nativo",
    whatHappened: "La conversión de la web móvil mejoró y aún no se necesitaba app", lesson: "Ajusta la plataforma a cómo la gente realmente reserva.",
  },
  19: {
    title: "Prometer una fecha de Q3 para cuentas multiusuario",
    options: ["Prometer la fecha de Q3", "Dar un rango de trimestre en su lugar"],
    gutOpt: "Prometer la fecha de Q3", worry: "El trabajo de autenticación no está acotado",
    finalOpt: "Prometer la fecha de Q3", why: "Una cuenta grande lo estaba esperando",
    gaveUp: "Margen para equivocarse", tripwire: "Si el scope de autenticación crece, ampliar la fecha a un rango",
    whatHappened: "La autenticación fue más grande de lo esperado y la fecha se movió un mes", lesson: "Mucha confianza en trabajo de autenticación no acotado es una señal de alerta.",
  },
  20: {
    title: "Cambiar de proveedor de email o quedarse",
    options: ["Quedarse con el proveedor actual", "Cambiar a un nuevo proveedor"],
    gutOpt: "Quedarse con el proveedor actual", worry: "La migración rompe la entregabilidad",
    finalOpt: "Cambiar a un nuevo proveedor", why: "La entregabilidad venía bajando y el soporte era lento",
    gaveUp: "Un statu quo estable", tripwire: "Si las tasas de rebote suben tras el cambio, revertir",
    whatHappened: "La entregabilidad se recuperó en una semana tras el cambio", lesson: "Un proveedor que te ignora ya es un riesgo.",
  },
  21: {
    title: "Prometer la fecha del roadmap Q2 en la presentación de la junta",
    options: ["Poner la fecha en la presentación", "Mostrar un rango en la presentación"],
    gutOpt: "Poner la fecha en la presentación", worry: "La presentación se vuelve un compromiso",
    finalOpt: "Poner la fecha en la presentación", why: "La junta quería detalles y yo me sentía bien con el plan",
    gaveUp: "Flexibilidad", tripwire: "Si algún hito se mueve, avisar a la junta antes de que pase la fecha",
    whatHappened: "La fecha se movió tres semanas y fue incómodo en la siguiente reunión de la junta", lesson: "Una fecha en una presentación de junta es una promesa, no un plan.",
  },
  22: {
    title: "Promover desde dentro o contratar un gerente de diseño",
    options: ["Promover una diseñadora sénior", "Contratar un gerente de diseño"],
    gutOpt: "Promover una diseñadora sénior", worry: "Le faltan habilidades de gestión",
    finalOpt: "Promover una diseñadora sénior", why: "Ya lideraba al equipo informalmente y lo quería",
    gaveUp: "Experiencia de gestión externa", tripwire: "Si tiene problemas con el trabajo de personas, conseguirle un coach",
    whatHappened: "Creció en el rol con algo de coaching", lesson: "Promueve a la persona que el equipo ya sigue.",
  },
  23: {
    title: "Añadir un nivel gratuito o seguir solo de pago",
    options: ["Seguir solo de pago", "Añadir un nivel gratuito limitado"],
    gutOpt: "Añadir un nivel gratuito limitado", worry: "Los usuarios gratuitos nunca convierten",
    finalOpt: "Añadir un nivel gratuito limitado", why: "Los pros independientes necesitaban una entrada antes de pagar",
    gaveUp: "Precios simples", tripwire: "Si la conversión sigue bajo el 5 por ciento, repensar el nivel",
    whatHappened: "La conversión de gratuito a pago quedó cerca del 8 por ciento", lesson: "Un nivel gratuito estrecho puede ser una verdadera puerta de entrada.",
  },
  24: {
    title: "Retrasar el cambio de precios hasta después de la temporada de renovaciones",
    options: ["Lanzar los precios ahora", "Esperar hasta después de las renovaciones"],
    gutOpt: "Esperar hasta después de las renovaciones", worry: "Dejamos dinero sobre la mesa",
    finalOpt: "Esperar hasta después de las renovaciones", why: "Un cambio de precio a mitad de renovación asustaría a las cuentas",
    gaveUp: "Ingresos más rápidos", tripwire: "Si aparecen señales de churn, esperar más",
    whatHappened: "Las renovaciones cerraron limpias y los precios se lanzaron después con bajo churn", lesson: "Programar el cambio de precio alrededor de las renovaciones valió la pena.",
  },
  25: {
    title: "Recortar la función de sincronización de calendario del launch de primavera",
    options: ["Mantener la sincronización de calendario en primavera", "Recortarla a un launch posterior"],
    gutOpt: "Mantener la sincronización de calendario en primavera", worry: "Los usuarios avanzados están esperando",
    finalOpt: "Recortarla a un launch posterior", why: "Estaba frenando el launch y solo una parte de los usuarios la necesitaba",
    gaveUp: "Una función que los usuarios avanzados querían", tripwire: "Si el churn se relaciona con la sincronización, adelantarla",
    whatHappened: "El launch salió limpio y la sincronización llegó después con un mejor diseño", lesson: "Recortar la función lenta mejoró todo el launch.",
  },
  26: {
    title: "Dar retroalimentación dura a un líder querido",
    options: ["Tener la conversación directa", "Dejarlo pasar otro ciclo"],
    gutOpt: "Dejarlo pasar otro ciclo", worry: "Agria la relación",
    finalOpt: "Tener la conversación directa", why: "Su planificación fallaba y el equipo lo sentía",
    gaveUp: "Unas semanas fáciles", tripwire: "Si la planificación no mejora en un ciclo, escalar",
    whatHappened: "La conversación fue dura pero la planificación mejoró después", lesson: "El líder querido también necesita la nota honesta.",
  },
  27: {
    title: "Construir la lógica de agendamiento en casa o comprarla",
    options: ["Construirla en casa", "Licenciar un motor de agendamiento"],
    gutOpt: "Construirla en casa", worry: "Reinventamos una rueda difícil",
    finalOpt: "Construirla en casa", why: "El agendamiento era nuestro núcleo y lo genérico no encajaba con servicios a domicilio",
    gaveUp: "Un inicio más rápido", tripwire: "Si la construcción se estanca dos sprints, reevaluar comprar",
    whatHappened: "El motor interno encajó con el dominio y se volvió un diferenciador", lesson: "Construye lo que realmente es tu producto.",
  },
  28: {
    title: "Lanzar el dashboard con dos gráficos o cinco",
    options: ["Lanzar los cinco gráficos", "Lanzar dos e iterar"],
    gutOpt: "Lanzar los cinco gráficos", worry: "Dos se siente poco",
    finalOpt: "Lanzar dos e iterar", why: "Dos respondían las preguntas principales y podíamos aprender del uso",
    gaveUp: "Una primera versión más completa", tripwire: "Si los usuarios piden los otros gráficos, añadirlos",
    whatHappened: "Los dos gráficos cubrieron la mayoría de las necesidades y los siguientes dos fueron guiados por datos", lesson: "Lanza los gráficos que la gente pide, no los que imaginas.",
  },
  29: {
    title: "Comprometer una fecha para los registros de auditoría de Acme",
    options: ["Comprometer una fecha firme a Acme", "Darle a Acme un mes objetivo"],
    gutOpt: "Comprometer una fecha firme a Acme", worry: "La construcción toca pagos",
    finalOpt: "Comprometer una fecha firme a Acme", why: "Acme estaba a punto de firmar y quería certeza",
    gaveUp: "Un margen de seguridad", tripwire: "Si la construcción toca pagos, añadir margen antes de cotizar",
    whatHappened: "La fecha se movió dos veces y Acme escaló a su patrocinador ejecutivo", lesson: "Suma el peor caso de Marco antes de darle una fecha a un cliente.",
  },
  30: {
    title: "Mover el logging a un servicio gestionado",
    options: ["Mantener el logging autoalojado", "Cambiar a un servicio de logging gestionado"],
    gutOpt: "Mantener el logging autoalojado", worry: "Costo y dependencia",
    finalOpt: "Cambiar a un servicio de logging gestionado", why: "El equipo pasaba días en infraestructura de logs en lugar de producto",
    gaveUp: "Control total del stack", tripwire: "Si los costos pasan del presupuesto, limitar la retención",
    whatHappened: "El equipo recuperó días y la respuesta a incidentes se aceleró", lesson: "Deja de alojar lo que no es tu producto.",
  },
  31: {
    title: "Fijar una fecha de launch antes de la revisión de seguridad",
    options: ["Fijar la fecha ahora", "Esperar la revisión de seguridad"],
    gutOpt: "Fijar la fecha ahora", worry: "La revisión encuentra algo",
    finalOpt: "Fijar la fecha ahora", why: "Marketing quería una fecha alrededor de la cual construir",
    gaveUp: "Una aprobación limpia primero", tripwire: "Si la revisión marca algo, mover la fecha",
    whatHappened: "La revisión marcó un problema y la fecha se movió una semana", lesson: "No fijes una fecha alrededor de una revisión que no has terminado.",
  },
  32: {
    title: "Rotar a un ingeniero fuera de un proyecto que ama",
    options: ["Rotarlo a la nueva área", "Dejarlo donde está"],
    gutOpt: "Rotarlo a la nueva área", worry: "Pierde motivación",
    finalOpt: "Rotarlo a la nueva área", why: "Era la persona correcta para un área estancada y era un movimiento de crecimiento",
    gaveUp: "Su comodidad", tripwire: "Si se desconecta, revisar en un mes",
    whatHappened: "Destrabó la nueva área y agradeció el cambio", lesson: "Una rotación puede ser un regalo si la planteas como crecimiento.",
  },
  33: {
    title: "Contratar una diseñadora sénior ahora o esperar el presupuesto de Q1",
    options: ["Contratar ahora contra el presupuesto de este año", "Esperar el presupuesto de Q1"],
    gutOpt: "Contratar ahora contra el presupuesto de este año", worry: "Resistencia del presupuesto",
    finalOpt: "Contratar ahora contra el presupuesto de este año", why: "La candidata era excepcional y el rediseño la necesitaba",
    gaveUp: "Una línea de presupuesto más limpia", tripwire: "Si el presupuesto es cuestionado, justificar con el scope del rediseño",
    whatHappened: "La contratación se concretó e impulsó el rediseño más de lo esperado", lesson: "Para una candidata excepcional, contrata antes del calendario de presupuesto.",
  },
  34: {
    title: "Añadir permisos por rol ahora o después del launch",
    options: ["Construir permisos antes del launch", "Lanzar plano, añadir roles después"],
    gutOpt: "Lanzar plano, añadir roles después", worry: "Enterprise necesita roles desde el día uno",
    finalOpt: "Construir permisos antes del launch", why: "Dos tratos dijeron que los roles eran un requisito indispensable",
    gaveUp: "Un launch más temprano", tripwire: "Si los roles retrasan el launch más de un mes, lanzar plano primero",
    whatHappened: "Los roles tomaron más de lo planeado y empujaron el launch tres semanas", lesson: "Verifica que un requisito indispensable realmente lo sea antes de que mueva la fecha.",
  },
  35: {
    title: "Retrasar el launch una semana para corregir el bug de onboarding",
    options: ["Lanzar a tiempo con el bug", "Retrasar una semana y corregirlo"],
    gutOpt: "Retrasar una semana y corregirlo", worry: "Perdemos la ventana de launch",
    finalOpt: "Retrasar una semana y corregirlo", why: "El bug afectaba a usuarios nuevos en su primera reserva",
    gaveUp: "El día de launch original", tripwire: "Si la corrección pasa de una semana, lanzar con una nota de problema conocido",
    whatHappened: "Corregido en una semana y lanzado limpio sin tickets de onboarding", lesson: "Una semana para proteger la primera impresión vale la pena.",
  },
  36: {
    title: "Dejar ir a una contratación con problemas o extender su adaptación",
    options: ["Extender la adaptación con un plan", "Separar caminos ahora"],
    gutOpt: "Extender la adaptación con un plan", worry: "Solo lo estamos retrasando",
    finalOpt: "Extender la adaptación con un plan", why: "Mostraba señales de lograrlo y merecía una oportunidad justa",
    gaveUp: "Un reinicio más rápido", tripwire: "Si no hay progreso en un mes, separar caminos",
    whatHappened: "La adaptación no funcionó y separamos caminos un mes después de todos modos", lesson: "Cuando el instinto dice que estás retrasando, hazle caso antes.",
  },
  37: {
    title: "Comprometer una fecha de demo a un prospecto antes de la construcción",
    options: ["Comprometer la fecha de la demo", "Ofrecer una ventana de demo"],
    gutOpt: "Comprometer la fecha de la demo", worry: "La función apenas está empezada",
    finalOpt: "Comprometer la fecha de la demo", why: "El prospecto estaba interesado y quería verla en vivo",
    gaveUp: "Un margen realista", tripwire: "Si la construcción no está lista para demo tres días antes, reprogramar pronto",
    whatHappened: "La demo fue difícil porque la función no estaba lista y el trato se enfrió", lesson: "No fijes una fecha de demo para una función que apenas está empezada.",
  },
  38: {
    title: "Retirar el viejo sistema de notificaciones en 90 días",
    options: ["Retirar en 90 días", "Mantener ambos sistemas funcionando"],
    gutOpt: "Retirar en 90 días", worry: "Algunas cuentas se pierden el cambio",
    finalOpt: "Retirar en 90 días", why: "Dos sistemas duplicaban la carga de mantenimiento",
    gaveUp: "Una migración lenta y segura", tripwire: "Si la migración se retrasa en el día 60, extender la ventana",
    whatHappened: "El volumen de tickets de soporte se disparó por cuentas confundidas y Priya no fue avisada a tiempo", lesson: "Avísale a Priya antes de un retiro, no después de que lleguen los tickets.",
  },
  39: {
    title: "Incluir la vista móvil en el rediseño o diferirla",
    options: ["Rediseñar solo escritorio primero", "Rediseñar escritorio y móvil juntos"],
    gutOpt: "Rediseñar solo escritorio primero", worry: "Móvil se queda atrás de nuevo",
    finalOpt: "Rediseñar escritorio y móvil juntos", why: "La mitad de las reservas eran móviles y una experiencia dividida confundiría a los pros",
    gaveUp: "Un launch de escritorio más rápido", tripwire: "Si móvil frena el calendario, lanzar escritorio y dar seguimiento rápido",
    whatHappened: "Ambos se lanzaron juntos y la experiencia se sintió consistente", lesson: "Cuando la mitad de tu tráfico es móvil, no lo difieras.",
  },
  40: {
    title: "Pausar la prueba del programa de referidos",
    options: ["Mantener la prueba de referidos activa", "Pausar y reelaborarla"],
    gutOpt: "Pausar y reelaborarla", worry: "Perdemos el poco impulso que tenía",
    finalOpt: "Pausar y reelaborarla", why: "Las recompensas eran confusas y los registros estaban planos",
    gaveUp: "Un experimento en vivo", tripwire: "Si la versión reelaborada también prueba plana, abandonar los referidos",
    whatHappened: "Pausar liberó al equipo y la versión reelaborada probó mejor después", lesson: "Un incentivo confuso vale la pena pausarlo para corregirlo.",
  },
}
